### ISSUE TITLE
local image/font

### ISSUE THREAD

**Issue by edon2005** [tech4242/wkwebview-local-resources#1]
Hi,

Is it possible to load images/font/css by loadHTML if file html is not in Bundle but just loaded by user, for example in Document folder of Application?

Thanks

**Comment by tech4242** [comment]
Hi @edon2005, 

I think I'll need some additional info. How would your setup be different from the current one? If that Document folder is in your app then it has to be a part of your Bundle right? Feel free to send me your app's structure so we can figure this out :) 

Cheers

**Comment by edon2005** [comment]
Hi @tech4242,

For example - I download zip archive from server and unzip it in Documents. The zip archive has file.html, file.css, file.jpg, file.ttf.
So Documents contain: 
Sub Folder 1 /
   and in Subfolder contain:
   file.html
   file.css
   file.jpg
   file.ttf
and WKWebView did not see them at all (except html)...

**Comment by tech4242** [comment]
Ok, got it. Will have to try this one out. Will keep you posted!

**Comment by edon2005** [comment]
Thanks a lot! :)

**Comment by tech4242** [comment]
@edon2005 I'll have a look right now. Let's see what I come up with

**Comment by tech4242** [comment]
@edon2005 added the functionality as you requested. Took me longer than expected tbh :) will add it to my StackOverflow answer as well. Now is as good a time as any to star the repo ;)

**Comment by edon2005** [comment]
@tech4242  did you get success in it????

**Comment by tech4242** [comment]
@edon2005 yup just read the README

**Comment by edon2005** [comment]
@tech4242 It work in simulator, but on real device nope :(

**Comment by tech4242** [comment]
@edon2005 aaand fixed for my iPhone X :) The magic is using `webView.loadFileURL(htmlURL, allowingReadAccessTo: folderURL!)` instead and setting `allowingReadAccessTo` to the whole folder and not just your html file - found that out in the last second before giving up haha

**Comment by edon2005** [comment]
@tech4242 But you do 
```
                    webView.loadFileURL(htmlURL, allowingReadAccessTo: folderURL!)
```
instaed of 
```
                webView.loadHTMLString(htmlString as String, baseURL: baseUrl)

```
It is a little different

**Comment by tech4242** [comment]
LOC 79: `webView.loadFileURL(htmlURL, allowingReadAccessTo: folderURL!)` ViewController.swift. It's the same thing. My baseUrl in loadFileURL is sort of what gets passed to allowingReadAccessTo. It basically tells webView what it can access on your iPhone's app container. It's a different method

**Comment by edon2005** [comment]
@tech4242  Correctly, but the question is how to use webView.loadHTMLString. Because for exmaple you need to do some js injections.

**Comment by tech4242** [comment]
won't work with loadHTMLString because baseUrl doesn't seem to work on devices like it does in the Simulator. That one I can't solve. Why not just add another JS file that has your JS code as a workaround?

**Comment by edon2005** [comment]
@tech4242 because html files in zip are around the internet. They are not mine. And here is 2 decision I see:
1. Use GDWebServer. 
2. Rewrite content of that files with injections and opened them again.

**Comment by tech4242** [comment]
Depends on your usecase I guess. What I meant was that you could just add a <script> tag to your downloaded HTML pages with your own .js file and *then* start loading the page. Will be simpler than dumping js as string into your HTML pages.
